### ISSUE TITLE
Background does not follow overlong code block 

### ISSUE THREAD

**Issue by bebehei** [eliasson/liquorice#13]
Having an overlong code-block, will enhance the code-block with a scrollbar. If you scroll, the background does not follow the content.

I think this explains it best:

Normal view:

![screenshot from 2017-09-12 18-12-17](https://user-images.githubusercontent.com/2073458/30336600-f8af4560-97e5-11e7-851d-83f49bee0683.png)

Scrolled:

![screenshot from 2017-09-12 18-12-31](https://user-images.githubusercontent.com/2073458/30336598-f884d79e-97e5-11e7-9f43-d64379f6d779.png)

Is it fixable to have the background expand over the whole content?

**Comment by eliasson** [comment]
I have not been able to reproduce this issue on OSX (Chrome, Safari, Firefox) or Linux (Firefox).

What OS and browser are you running? And how does the generated HTML look like?

**Comment by bebehei** [comment]
Hi @eliasson, thanks for your reply.

I'm using Firefox nightly on Linux. I also tested it on Chromium and there is the same behavior.

 The page is already live at https://dunst-project.org/faq/

**Comment by eliasson** [comment]
@bebehei the reason seems to be that your site is not using _article_ as the _Content Type_ and previously the styling only was applied to `.li-article`. I just made a commit that applies the styling for base elements.

Please let me know if this resolves your issue.

**Comment by bebehei** [comment]
Thank you for your fast reply. It did not work on the first try. [It turns out that, the our website also uses incompatible overwrites and this bug results by a combination of both.](https://github.com/dunst-project/dunst-project.org/blob/85f759c41bad0bb2757b01cf367c80a23aacdafd/static/css/global.css#L9) 🙈

It works now like a charm.

@eliasson Could you please update also the minified css file? Both files are currently not in sync. After that, this bug is definitely fixed.

Sorry for the noise.

**Comment by eliasson** [comment]
Great. The minified CSS is also updated now.
