### ISSUE TITLE
How to add static page?

### ISSUE THREAD

**Issue by 3835** [eliasson/liquorice#8]
Hi!
Thank you for awesome theme! I have a silly question, how can I add a static page (
as in the demo http://themes.gohugo.io/theme/liquorice/)?

**Comment by eliasson** [comment]
What do you mean with static page? All pages in hugo are static. Use

    $ hugo add foo.md
    $ hugo serve --theme=liquorice
 
You can now view that page at url http://localhost:1313/foo/

**Comment by 3835** [comment]
Yes, yes know that all hugo pages are static. I'm sorry, I asked the wrong question, 
I mean how to add a menu for "static" page like "About Hugo", "tutorial", etc. from demo. 
![screen](http://malanow.net/screen.png)

**Comment by eliasson** [comment]
Hugo has a feature called Menus, where you can add menu items in your site's configuration file, e.g. in `config.toml` you can add:

```
[[menu.main]]
    name = "foo"
    url = "/foo/"

[[menu.main]]
    name = "Google"
    url = "http://www.google.com"
```

Liquorice theme renders the `main` menu in the page header.

You can read more on the subject here https://gohugo.io/extras/menus/

**Comment by 3835** [comment]
Now it is simple :)
